import type { Metadata } from "next";
import "./globals.css";
import { SiteFooter } from "./site-footer";
import { SiteHeader } from "./site-header";

export const metadata: Metadata = {
  title: "DPDing",
  description: "Generated by create next app",
};

// Chrome 135+ on Android resizes the layout viewport (and re-resolves svh)
// mid-scroll as its URL bar and edge-to-edge bottom "chin" retract, so
// svh-bound sections visibly change height while scrolling. Pin the viewport
// height into --stable-vh at first paint and only remeasure when the width
// changes (rotation/real resize), never on height-only browser-UI churn.
const stableVhScript = `(function(){var d=document.documentElement;var w=window.innerWidth;function set(){d.style.setProperty("--stable-vh",window.innerHeight+"px")}set();window.addEventListener("resize",function(){if(window.innerWidth===w)return;w=window.innerWidth;set()})})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: stableVhScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <SiteHeader />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
